In [5]:
# Create a null vector of size 10 but the fifth value which is 1.

import numpy as np
x = np.zeros(10)
print(x)
print("Update fifth value to 1")
x[5] = 1
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update fifth value to 1
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [11]:
# Create a vector with values ranging from 10 to 49.

v = np.arange(10,50)
print("Values:")
print(v)

Values:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [10]:
# Create a 3x3 matrix with values ranging from 0 to 8.

x =  np.arange(0, 9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [13]:
# Find indices of non-zero elements from [1,2,0,0,4,0].

x = [1,2,0,0,4,0]
np.nonzero(x)

(array([0, 1, 4], dtype=int64),)

In [17]:
# Create a 10x10 array with random values and find the minimum and maximum values.

x = np.random.random((10,10))
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Minimum and Maximum Values:
0.0071826603528236665 0.9958211089247694


In [20]:
# Create a random vector of size 30 and find the mean value.

v = np.random.random(30)
x = v.mean()
print(x)

0.46312301803721106
